language: ruby
sudo: false
rvm:
  - 2.3.3

services:
  - postgresql
  - redis-server
  - elasticsearch

addons:
  postgresql: "9.5.5"

before_script:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.1/elasticsearch-2.3.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.1.deb && sudo service elasticsearch restart
  - sleep 10
  - psql -c 'create database fractal_test;' -U postgres

install: gem install rails

bundler_args: --without production

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
